<a href="https://colab.research.google.com/github/Mohammed-Khan6/wia1007w3/blob/main/wia1007w3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
# cell 1: import
import numpy as np
np.__version__  # shows numpy version


'2.0.2'

In [7]:
# 2x2 array (example with random floats)
arr_2x2 = np.random.random((2,2))
print("2x2 array:\n", arr_2x2)


2x2 array:
 [[0.0259408  0.38213694]
 [0.58478771 0.33280362]]


In [8]:
arr_3x4 = np.random.random((3,4))
print("3x4 array:\n", arr_3x4)


3x4 array:
 [[0.93767238 0.50296514 0.84763838 0.26073632]
 [0.94498523 0.56217809 0.45207887 0.69636284]
 [0.98874697 0.17275501 0.88689512 0.54357995]]


In [9]:
ones_3x3 = np.ones((3,3))
zeros_2x4 = np.zeros((2,4))
print("ones_3x3:\n", ones_3x3)
print("zeros_2x4:\n", zeros_2x4)


ones_3x3:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
zeros_2x4:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
# choose dimensions
n = 4
p = 5
m = 3

A = np.random.random((n,p))
B = np.random.random((p,m))

# matrix multiplication: result shape (n,m)
C = np.dot(A, B)     # or A @ B
print("A shape:", A.shape)
print("B shape:", B.shape)
print("A dot B shape:", C.shape)
print("A dot B:\n", C)


A shape: (4, 5)
B shape: (5, 3)
A dot B shape: (4, 3)
A dot B:
 [[0.68346882 0.7239698  1.29062982]
 [1.03624073 1.02539685 1.74888347]
 [0.65190223 0.86408778 1.17373694]
 [0.97183221 0.93417387 1.61712582]]
